version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - ls -la
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - mkdir -p scripts
      - zip -r deployment-package.zip build/libs/backend-0.0.1-SNAPSHOT.jar appspec.yml scripts/

cache:
  paths:
    - '/root/.gradle/caches/**/*'

artifacts:
  files:
    - 'appspec.yml'
    - 'build/libs/backend-0.0.1-SNAPSHOT.jar'
    - 'scripts/**'
