version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - ls -la
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'

artifacts:
  files:
    - 'appspec.yml'
    - 'build/libs/backend-0.0.1-SNAPSHOT.jar '
    - 'scripts/**'
  type: zip
  name: build-output.zip
