name: Assign Reviewer By Label
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GET ASSIGNEES
        env:
          PULL_REQUEST_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "EVENT : $GITHUB_CONTEXT"
          assignees=$(echo "$PULL_REQUEST_CONTEXT" | jq -r '.assignees[].login' | tr '\n' ', ' | sed 's/, $//' | rev | cut -c 3- | rev)
          echo "ASSIGNEES : $assignees"
#
#      - name: LOG ASSIGNEE
#        run: |
#          static_reviewers=("i894" "youngsu5582")
#          echo "STATIC: $static_reviewers"
#          echo "STATIC: ${static_reviewers}"
#
#
#          echo "ASSIGNEES : $unique_reviewers"
#          echo "ASSIGNEES=$unique_reviewers" >> $GITHUB_ENV
#
#      - name: Backend Label
#        uses: wow-actions/auto-assign@v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          reviewers: i894, youngsu5582
#          assignees: ${{ env.ASSIGNEES }}
#          includeLabels: BE
