name: Assign Reviewer By Label
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: LOG ASSIGNEE
        run: |
          assignees=$(echo "${{ github.event.pull_request }}" | jq -r '.assignees[].login' | tr '\n' ', ' | sed 's/, $//' | rev | cut -c 3- | rev)
          
          echo "ASSIGNEES : $ASSIGNEES"
          echo "ASSIGNEES=$assignees" >> $GITHUB_ENV

      - name: Backend Label
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: i894, youngsu5582
          assignees: ${{ env.assignees }}
          includeLabels: BE
