name: Assign Reviewer By Label
on:
  pull_request:
    types:
      - edited
      - labeled
jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: All Label
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ashsty, jcoding-play, hjk0761, youngsu5582
          assignees: ${{ github.event.pull_request.user.login }}
          includeLabels: ALL

      - name: Backend Label
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ashsty, jcoding-play, hjk0761, youngsu5582
          assignees: ${{ github.event.pull_request.user.login }}
          includeLabels: BE
