name: Backend CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: query_reports/query_coverage_report.html

      - name: Debugging
        run: |
          ls -al
          pwd
          ls -al query_reports

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: query_reports
