name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Issue Detail
        run: |          
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "https://api.github.com/repos/${{ github.repository }}/issues/46")

          echo "ASSIGNEE : $(echo "$response" | jq -r '.assignees[].login' | tr '\n' ', ' | sed 's/, $//')"
          echo "LEGACY_LABELS : $(echo "$response" | jq -r '.labels[].name')"
          echo "REFACTOR_LABELS : $(echo "$response" | jq -r '.labels[].name' | tr '\n' ', ')" 
          echo "LABELS : $(echo "$response" | jq -r '.labels[].name' | tr '\n' ', ' | sed 's/, $//')"
          echo "TITLE : $(echo "$response" | jq -r 'title')"
          echo "RESPONSE : $response"
          
          
