name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print GitHub context variables
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Ref: ${{ github.ref }}"

      - name: Print Runner context variables
        run: |
          echo "OS: ${{ runner.os }}"
          echo "Temp Directory: ${{ runner.temp }}"
          echo "Tool Cache: ${{ runner.tool_cache }}"
